# Generated by Django 3.1.7 on 2021-03-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210327_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactName', models.CharField(max_length=100)),
                ('contactEmail', models.CharField(max_length=100)),
                ('contactMessage', models.CharField(max_length=500)),
            ],
        ),
    ]
