# Generated by Django 3.1.7 on 2021-03-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='contactMessage',
            field=models.TextField(),
        ),
    ]
