# Generated by Django 3.1.7 on 2021-04-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210331_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='myfile',
            field=models.FileField(null=True, upload_to='media/%Y/%m/%d/'),
        ),
    ]
