# Generated by Django 3.1.7 on 2021-04-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210427_1219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='upload',
        ),
        migrations.AddField(
            model_name='registration',
            name='myfile',
            field=models.FileField(default='', editable=False, upload_to='media/'),
        ),
    ]
