# Generated by Django 3.1.7 on 2021-05-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210517_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuploadfile',
            name='f_name',
        ),
    ]
