# Generated by Django 3.1.7 on 2021-05-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_myuploadfile_f_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuploadfile',
            name='f_name',
        ),
    ]
