# Generated by Django 3.1.7 on 2021-05-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_myuploadfile_f_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuploadfile',
            name='f_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
