# Generated by Django 3.1.7 on 2021-05-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_myuploadfile_f_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuploadfile',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='myuploadfile',
            name='myfile',
        ),
        migrations.AddField(
            model_name='registration',
            name='myfile',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
