# Generated by Django 3.1.7 on 2021-05-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20210521_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='myuploadfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myfile', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='registration',
            name='myfile',
        ),
    ]
