# Generated by Django 3.1.7 on 2021-05-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20210521_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuploadfile',
            name='f_name',
            field=models.CharField(default='file1', max_length=100),
            preserve_default=False,
        ),
    ]
